.gitignore
.npmignore
.travis.yml
bin/deploy-gh-pages.sh
package-lock.json
package.json

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

[WIP] Deploy to github pages and npm

---

e2e/custom-logger.e2e-spec.ts
lib/interfaces/terminus-module-options.interface.ts
lib/terminus-bootstrap.service.ts

```
[ ] Bugfix
[x] Feature
```
Issue Number: #19

feat(core): Add ability to configure logger

---

package.json

```
[ ] Bugfix
[x] Feature
```
https://github.com/nestjs/terminus/issues/23

fix(build): Move mysql to devdependencies

---

e2e/custom-logger.e2e-spec.ts
e2e/fasitfy.e2e-spec.ts
e2e/health-checks/database.health.e2e-spec.ts
e2e/health-checks/dns.health.e2e-spec.ts
e2e/helper/bootstrap-module.ts
lib/terminus-bootstrap.service.ts
package-lock.json
package.json
sample/000-dogs-app/package-lock.json
sample/000-dogs-app/package.json
sample/000-dogs-app/src/main.ts
tslint.json

```
[x] Bugfix
[ ] Feature
```
Does not work with FastifyAdapter
Issue Number: #24
Should work with FasitfyAdapter
```
[ ] Yes
[ ] No
```

test(bootstrap): Add e2e test case for FastifyAdapter

---

lib/terminus-core.module.ts
lib/terminus.module.ts
lib/utils/promise-timeout.ts
package-lock.json
package.json
tsconfig.json
tslint.json

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

build: Stricter tsconfig type checking

---

sample/000-dogs-app/package.json
sample/000-dogs-app/test/health.e2e-spec.ts
sample/000-dogs-app/test/jest-e2e.json

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

sample(000): Add e2e test for healthmodule

---

.travis.yml
Dockerfile
lib/health-indicators/database/mongoose.health.ts
lib/health-indicators/database/typeorm.health.ts
lib/health-indicators/dns/dns.health.ts
lib/health-indicators/microservice/grpc.health.ts
lib/health-indicators/microservice/microservice.health.ts
lib/interfaces/terminus-module-options.interface.ts
lib/terminus-bootstrap.service.ts
lib/terminus-core.module.ts
sample/000-dogs-app/package-lock.json
sample/001-mongoose-app/package-lock.json
sample/002-microservice-app/package-lock.json
sample/003-memory-app/package-lock.json
sample/004-grpc-app/package-lock.json
tsconfig.json

```
[ ] Bugfix
[ ] Feature
[x] Code style update (formatting, local variables)
```
Use `strict` option in TSConfig
```
[ ] Yes
[x] No
```

chore(): Use strict config in tsconfig

---

lib/health-indicators/database/typeorm.health.ts

```
[ ] Bugfix
[x] Feature
```
Issue Number: #222 
Add support for MongoDB when using `TypeOrmHealthIndicator`.
```
[ ] Yes
[x] No
```

feat(typeorm): Add mongo support

---

e2e/fasitfy.e2e-spec.ts
e2e/health-checks/disk.health.e2e-spec.ts
e2e/health-checks/dns.health.e2e-spec.ts
e2e/health-checks/memory.health.e2e-spec.ts
e2e/health-checks/microservice.health.e2e-spec.ts
e2e/health-checks/mongoose.health.e2e-spec.ts
e2e/health-checks/typeorm.health.e2e-spec.ts
package-lock.json
package.json
sample/000-dogs-app/package-lock.json
sample/000-dogs-app/package.json
sample/001-mongoose-app/package-lock.json
sample/001-mongoose-app/package.json
sample/002-microservice-app/package-lock.json
sample/002-microservice-app/package.json
sample/003-memory-app/package-lock.json
sample/003-memory-app/package.json
sample/004-grpc-app/package-lock.json
sample/004-grpc-app/package.json

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

Deps/godaddy terminus 4.1.2

---

lib/interfaces/terminus-module-options.interface.ts
lib/terminus-bootstrap.service.spec.ts
lib/terminus-bootstrap.service.ts
package-lock.json

Resolves #228
```
[ ] Bugfix
[ ] Feature
```
Issue Number: #228 
Adds a new option called `useGlobalPrefix?: boolean` which is available on `TerminusModuleOptions` and `TerminusEndpoint`.
```ts
const app = await NestFactory.create(ApplicationModule);
app.setGlobalPrefix('/api/v1');
...
TerminusModule.forRoot({
// Change the default option of all endpoints to use the global prefix
useGlobalPrefix: true,
endpoints: [
{
// Will result /liveness
url: '/liveness',
useGlobalPrefix: false,
healthIndicators: …
```

feat(bootstrap): Add `useGlobalPrefix` option

---

lib/PACKAGE.md
lib/errors/connection-not-found.error.ts
lib/errors/storage-exceeded.error.ts
lib/errors/timeout-error.ts
lib/errors/unhealthy-response-code.error.ts
lib/health-indicators/database/databse-ping-check-settings.interface.ts
lib/health-indicators/database/mongoose.health.ts
lib/health-indicators/database/typeorm.health.ts
lib/health-indicators/disk/disk-health-options.type.ts
lib/health-indicators/disk/disk.health.ts
lib/health-indicators/dns/dns.health.ts
lib/health-indicators/health-indicator.ts
lib/health-indicators/memory/memory.health.ts
lib/health-indicators/microservice/grpc.health.ts
lib/health-indicators/microservice/microservice.health.ts
lib/interfaces/health-indicator.interface.ts
lib/interfaces/terminus-module-options.interface.ts
lib/terminus.module.ts

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

API Docs comments

---

lib/errors/connection-not-found.error.ts
lib/errors/storage-exceeded.error.ts
lib/errors/timeout-error.ts
lib/errors/unhealthy-response-code.error.ts
lib/health-indicators/database/databse-ping-check-settings.interface.ts
lib/health-indicators/database/mongoose.health.ts
lib/health-indicators/database/typeorm.health.ts
lib/health-indicators/health-indicator.ts
lib/interfaces/health-indicator.interface.ts

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

docs(): Error constructors should be internal

---

.travis.yml
package-lock.json
package.json
sample/000-dogs-app/package-lock.json
sample/001-mongoose-app/package-lock.json
sample/002-microservice-app/package-lock.json
sample/003-memory-app/package-lock.json
sample/004-grpc-app/package-lock.json
tsconfig.json

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

ci(): Improve build jobs

---

lib/health-indicators/database/typeorm.health.ts

```
[x] Bugfix
[ ] Feature
```
Issue Number: #374 
`pingDb` method invokes a valid query for `oracle` connection types 
```
[ ] Yes
[x] No
```

bugfix(oracle): Support oracle connection for pingDb query

---

lib/terminus-bootstrap.service.spec.ts
lib/terminus-bootstrap.service.ts

Fixes #461
```
[x] Bugfix
[ ] Feature
```
Issue Number: #461 
```
[ ] Yes
[x] No
```

fix(): Do not bootstrap terminus in case no http server

---

lib/errors/index.ts
lib/errors/mongo-connection.error.ts
lib/health-indicators/database/typeorm.health.ts

```
[x] Bugfix
[ ] Feature
```
Issue Number: #547
```
[ ] Yes
[x] No
```

fix(typeorm): MongoDB connection always returns connected

---

lib/health-indicators/database/typeorm.health.ts

```
[x] Bugfix
[ ] Feature
```
Issue Number:  #545
```
[ ] Yes
[ ] No
```

fix(typeorm): Connection parameter error

---

lib/index.ts

Fixes #639
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

fix(): export HealthCheckResult to public interface

---

README.md

```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: documentation change
```
```
[ ] Yes
[x] No
```

docs(readme): state in readme that npm should save-install

---

lib/health-indicator/health-indicator.ts

```
[ ] Bugfix
[ ] Feature
[x] Code style update (formatting, local variables)
```
```
[ ] Yes
[x] No
```

style(): remove excess * and nl from tsdoc on getStatus

---

README.md

```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: fix documentation example code
```
```
[ ] Yes
[x] No
```

docs(readme): fix example code

---

sample/001-mongoose-app/package-lock.json
sample/001-mongoose-app/package.json

```
[ ] Bugfix
[ ] Feature
```
N/A
```
[ ] Yes
[x] No
```
This PR fix in sample/001-mongoose-app, the "@nestjs/terminus" dependency in package.json is missing

sample(001): Added dependency @nestjs/terminus

---

sample/001-mongoose-app/docker-compose.yml

```
[ ] Bugfix
[ ] Feature
```
N/A
```
[ ] Yes
[x] No
```
This PR added docker-compose for mongodb to try out sample-001

sample(001): Added docker-compose for mongodb

---

sample/000-dogs-app/package-lock.json
sample/000-dogs-app/package.json

```
[ ] Bugfix
[ ] Feature
```
N/A
```
[ ] Yes
[ ] No
```
This PR fix in sample/001-mongoose-app, the "@nestjs/terminus" and rxjs dependency in package.json is missing to try the sample

sample(001):Added dependency @nestjs/terminus and rxjs

---

sample/001-mongoose-app/src/health/health.controller.ts

```
[ ] Bugfix
[ ] Feature
```
N/A
```
[ ] Yes
[x] No
```
This PR added async function ping check mongoose

sample(001): Async function ping check mongoose

---

sample/000-dogs-app/src/health/health.controller.ts

```
[ ] Bugfix
[ ] Feature
```
N/A
```
[ ] Yes
[x] No
```
This PR added async function check

sample(000): Async function check

---

sample/README.md

```
[ ] Bugfix
[ ] Feature
```
N/A
```
[ ] Yes
[x] No
```
This PR fix little correction on readme

(sample): Fix readme on sample

---

sample/001-mongoose-app/package.json

```
[ ] Bugfix
[ ] Feature
```
N/A
```
[ ] Yes
[x] No
```
This PR removes the author field in package.json, in the "sample/001-mongoose-app" example, as in the other examples

sample(001): Removed author field in package.json

---

sample/005-typeorm-app/package.json

```
[ ] Bugfix
[ ] Feature
```
N/A
```
[ ] Yes
[x] No
```
This PR removes the author field in package.json, in the "sample/005-typeorm-app" example, as in the other examples

sample(005): Removed author field in package.json

---

.commitlintrc.json
package-lock.json
package.json

```
[ ] Bugfix
[x] Feature
```
N/A
```
[ ] Yes
[x] No
```
This PR, Added commilint

chore(commilint): added commilint

---

package.json

```
[ ] Bugfix
[ ] Feature
```
N/A
```
[ ] Yes
[x] No
```
This PR, Added type field in package.json

chore(): added type field in package.json

---

sample/000-dogs-app/src/health/health.module.ts

```
[ ] Bugfix
[ ] Feature
```
N/A
```
[ ] Yes
[x] No
```
This PR, fix indentation code

chroe(sample-000): fix indentation code

---

sample/000-dogs-app/src/app.module.ts
sample/000-dogs-app/src/main.ts

```
[ ] Bugfix
[ ] Feature
```
N/A
```
[ ] Yes
[x] No
```
This PR, rename app module

chore(sample-000): rename app module

---

sample/006-multi-db-typeorm-app/src/health/health.controller.ts
sample/006-multi-db-typeorm-app/src/health/health.module.ts

```
[ ] Bugfix
[ ] Feature
[ ] Other... Please describe: sample code fix
```
```
[ ] Yes
[x] No
```

sample: add missing multi-db connection names

---

CONTRIBUTING.md

```
[ ] Bugfix
[ ] Feature
```
N/A
```
[ ] Yes
[x] No
```
This PR, updated contribution guide for bugfix

docs(contributing): updated contribution guide for bugfix

---

lib/health-indicator/dns/dns.health.ts

```
[x] Code style update (formatting, local variables)
```
```
[ ] Yes
[x] No
```

style(dns): fix typo: ugprade → upgrade

---

lib/health-indicator/database/typeorm.health.ts

```
[x] Bugfix
[ ] Feature
```
Issue Number: #1102

Fix connection URL for MongoDB in TypeORM

---

sample/003-memory-app/src/health/health.module.ts

```
[ ] Bugfix
[ ] Feature
[x] Code style update (formatting, local variables)
```
There was an typo error on the import of **sample/003-memory-app/src/health/health.module.ts**
```
[ ] Yes
[ ] No
```

Fix typo error on import

---

lib/health-indicator/microservice/grpc.health.ts

```
[ ] Bugfix
[ ] Feature
```
Issue Number: #1422
the file `grpc.health.ts` should depends on `@grpc/grpc-js` package and not from the `grpc` package
```
[ ] Yes
[x] No
```
This PR, the file `grpc.health.ts` should depends on `@grpc/grpc-js` package and not from the `grpc` package

chore(): remove dependencies grpc

---

README.md

docs(readme): update logo

---

sample/001-mongoose-app/package-lock.json
sample/001-mongoose-app/package.json
sample/008-multi-database-mongoose-app/package-lock.json
sample/008-multi-database-mongoose-app/package.json

The package `@types/mongoose` is not used.
This PR removes the `@types/mongoose` dependency in the `001-mongoose-app` and `008-multi-database-mongoose-app` examples, because it is not necessary as the types are built into the mongoose 6.x package.

samples(): remove dependencies not used

---

package-lock.json
package.json

Removed dependencie `fastify-formbody` as it is deprecated and it appears that it is not used within the terminus package

chore(): remove dependencies not used

---

e2e/health-checks/microservice.health.e2e-spec.ts
lib/health-indicator/microservice/microservice.health.ts

There is currently no error being thrown when RMQ is down.
Issue Number: #1891
A `HealthCheckError` will be thrown when RMQ is down.

fix rmq health check

---

sample/002-microservice-app/package-lock.json
sample/002-microservice-app/package.json
sample/002-microservice-app/src/health/health.controller.ts

Issue Number: 1938
switch the Redis dependency package to [ioredis](https://github.com/luin/ioredis), use the `ioredis` options

fix(002-microservice-app): use ioredis and remove the url option

---

sample/002-microservice-app/src/health/health.controller.ts

The Redis port is wrong it is not `16379` but `6379`
Before with port `16379`
After with port `6379`

sample(002-microservie-app): fix port redis

---

lib/health-check/health-check-executor.service.ts

Issue Number: #1965
Runs health indicators in parallel instead of sequentially

perf: run health indicators in parallel

---

lib/health-indicator/http/axios.interfaces.ts

Issue Number: #2045
Added string type to `method` parameter in `AxiosRequestConfig` interface

chore(): update axios interface

---

lib/health-check/health-check-executor.service.spec.ts
lib/health-check/health-check-executor.service.ts

Fixes #2083
Issue Number: #2083

fix: HealthCheckError in sync HealthIndicatorFunction

---

sample/011-mirkoorm-app/.eslintrc.js
sample/011-mirkoorm-app/.gitignore
sample/011-mirkoorm-app/package-lock.json
sample/011-mirkoorm-app/package.json
sample/011-mirkoorm-app/src/app.module.ts
sample/011-mirkoorm-app/src/health/health.controller.ts
sample/011-mirkoorm-app/src/health/health.module.ts
sample/011-mirkoorm-app/src/main.ts
sample/011-mirkoorm-app/tsconfig.json

Proposal:
- Added a sample for using terminus  with mirkoorm
P.s. Terminus ♥️
I hope it can be useful to people using terminus with mirkoorm

sample(): added sample for mirkoorm app with terminus

---

lib/health-indicator/http/http.health.ts

Remove import not used (see screenshot)

chore(): remove import not used

---

lib/health-indicator/database/prisma.health.ts

Proposal:
- Marked the public api in prisma health

chore(): marked the public api in prisma health

---

lib/health-indicator/microservice/grpc.health.ts

Removed unused import ( see screenshot)

chore: removed unused import

---

e2e/graceful-shutdown.e2e-spec.ts
e2e/helper/bootstrap-testing-module.ts
lib/graceful-shutdown-timeout/graceful-shutdown-timeout.service.ts
lib/terminus.module.ts

test: add e2e test for graceful shutdown

---

e2e/health-checks/mikro-orm.health.e2e-spec.ts
lib/errors/database-not-connected.error.ts
lib/errors/messages.constant.ts
lib/health-indicator/database/mikro-orm.health.ts

fixes #2460
Issue Number: #2460

fix: mikroorm is indicated as up even when disconnected

---

e2e/health-checks/mikro-orm.health.e2e-spec.ts
lib/errors/database-not-connected.error.ts
lib/errors/messages.constant.ts
lib/health-indicator/database/mikro-orm.health.ts

fix: mikroorm is indicated as up even when disconnected (#2509)

---

lib/health-check/health-check.schema.ts

- [x ] Other... Please describe:
#2516 Fix additional props in openapi health schema
Described in issue.
Issue Number: #2516 
Described in issue.
- [x ] No

#2516 Fix additional props in openapi health schema

---

lib/health-indicator/database/typeorm.health.ts

typeorm MongoDB check create a new connection everytime and will cause more load on MongoDB
Reuse connection and run ping command
Tested manually in an environment health check passed from 40/50ms to 4/8ms:
```
[Nest] 8  - 05/04/2024, 9:49:48 AM     LOG [Network] 56b4c54a-c75a-4319-b9e9-12e3faa34542 - GET /health - 200 - 45ms
[Nest] 8  - 05/04/2024, 9:49:58 AM     LOG [Network] 4913ef85-c83b-4ce4-8b61-38cea5341868 - GET /health - 200 - 49ms
```
```
[Nest] 8  - 05/04/2024, 9:58:57 AM     LOG [Network] fb3aadb8-c4c0-4c15-b0cc-4302776747d4 - GET /health - 200 - 7ms
[Nest] 8  - 05/04/2024, 9:59:12 AM     LOG [Network] df4ad42a-d612-49a7-bfdf-27a9a6e0550f - GET /health - 200 - 5ms
```

change typeorm mongodb check
